### ISSUE TITLE
Isn't the last one M4 (instead of M6)?

### ISSUE THREAD

**Issue by claplace** [Elvynia/referentiel#1]
https://github.com/Elvynia/referentiel/blob/f7705c4721e4d6a9c8dc71e6f973645c579118ef/src/app/repository.service.ts#L132

**Comment by Elvynia** [comment]
Yes you're totally right ! Thank you for pointing this out, it's corrected now :)

EDIT -- https://elvynia.github.io/referentiel/ updated
